# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repositorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repositorie_id', models.IntegerField(verbose_name='ID')),
                ('repositorie_name', models.CharField(max_length=100, verbose_name='Nome')),
                ('repositorie_url', models.CharField(max_length=255, verbose_name='URL')),
                ('repositorie_language', models.CharField(max_length=20, verbose_name='Linguagem')),
            ],
            options={
                'verbose_name': 'Repositório',
                'verbose_name_plural': 'Repositórios',
            },
        ),
    ]
