# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 02:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170930_0138'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Repositorie',
            new_name='Repository',
        ),
    ]
