# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 02:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20171002_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='repositorie_id',
            new_name='repository_id',
        ),
    ]
